- name: Copy gateway executable
  copy:
    src: gateway
    dest: /root/gateway
    mode: +x

- name: Create gateway directory
  file:
    path: /root/web/src
    state: directory

- name: Copy gateway directory
  synchronize:
    src: src/
    dest: /root/web/src/
    mode: push


- name: Create gateway service file
  copy:
    content: |
      [Unit]
      Description=Gateway Service
      After=network.target

      [Service]
      ExecStart=/root/gateway
      WorkingDirectory=/root
      Restart=always

      Environment="GATEWAY_PASSWORD={{gateway_password}}"
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/gateway.service

- name: Enable and start gateway service
  systemd:
    name: gateway
    state: restarted
    daemon_reload: yes
    enabled: yes