- hosts: publicNginx
  user: root
  vars_files:
    - priv-vars.yaml
  tasks:

  - name: Install required packages
    apt:
      name:
        - nginx
        - certbot
        - python3-certbot-nginx
        - wget
        - curl
      state: present


  - name: Check if SSL certificate exists
    stat:
      path: "/etc/letsencrypt/live/unlock.{{ domain_name }}/fullchain.pem"
      follow: yes
    register: ssl_cert_exists

  - name: Generate
    shell: certbot certonly --nginx --non-interactive --agree-tos --email cert@{{ domain_name }} --domains data.{{ domain_name }}
    when: not ssl_cert_exists.stat.exists

  - name: Generate
    shell: certbot certonly --nginx --non-interactive --agree-tos --email cert@{{ domain_name }} --domains bit.{{ domain_name }}
    when: not ssl_cert_exists.stat.exists

  # Wait 10 seconds, the certs stopped being generated if you go too quick
  - name: Wait 10 seconds
    pause:
      seconds: 10

  - name: Generate
    shell: certbot certonly --nginx --non-interactive --agree-tos --email cert@{{ domain_name }} --domains home.{{ domain_name }}
    when: not ssl_cert_exists.stat.exists

  - name: Generate
    shell: certbot certonly --nginx --non-interactive --agree-tos --email cert@{{ domain_name }} --domains unlock.{{ domain_name }}
    when: not ssl_cert_exists.stat.exists

  - name: Renew SSL certificate
    shell: certbot renew --non-interactive
    when: ssl_cert_exists.stat.exists
