- name: Remove Wazuh agent
  hosts: all
  become: yes
  tasks:
    - name: Stop Wazuh agent service
      service:
        name: wazuh-agent
        state: stopped

    - name: Remove Wazuh agent package
      package:
        name: wazuh-agent
        state: absent
