- hosts: gitea
  user: oharris
  become: yes
  become_user: root
  vars:
    docker_user: oharris
  roles:
    - upgrader
    - docker
    - guest-agent
    - gitea

- hosts: vault
  user: root
  vars_files:
    - priv-vars.yaml
  roles:
    - upgrader
    - docker
    - vault

- hosts: casa
  user: oharris
  become: true
  roles:
    - upgrader
    - guest-agent
    - docker

- hosts: pihole
  roles:
    - upgrader
  tasks:
    - name: Update pihole
      shell: pihole -up

- hosts: caddy
  become: true
  user: oharris
  vars_files:
    - priv-vars.yaml
  roles:
    - upgrader
    - guest-agent
    - docker
    - caddy-local