- hosts: nextcloud
  user: root
  roles:
    - upgrader
    - guest-agent
    - docker
    - nextcloud
    - wazuh-agent
  

# - hosts: wazuh
#   user: root
#   roles:
#     - upgrader
#     - wazuhMaster

- hosts: tunnel-nginx
  user: oharris
  become: true
  become_user: root
  vars_files:
    - priv-vars.yaml
  roles:
    - upgrader
    - guest-agent
    - wazuh-agent
    - docker
    - nginx-tunneled
    # - caddy-local

- hosts: remote
  user: oharris
  become: yes
  roles:
    - upgrader
    - wazuh-agent
    - docker
    - caddy-remote
  vars:
    wazuh_address: 192.168.2.5
  vars_files:
    - priv-vars.yaml

- hosts: vault
  user: root
  vars_files:
    - priv-vars.yaml
  roles:
    - upgrader
    - wazuh-agent
    - docker
    - vault

- hosts: gitea
  user: oharris
  become: yes
  become_user: root
  vars:
    docker_user: oharris
  roles:
    - upgrader
    - wazuh-agent
    - docker
    - guest-agent
    - gitea