- hosts: nextcloud
  user: root
  roles:
    - upgrader
    - guest-agent
    - docker
    - nextcloud
    - wazuh-agent
  

- hosts: wazuh
  user: root
  roles:
    - upgrader
    - wazuh

- hosts: publicNginx
  user: root
  vars_files:
    - priv-vars.yaml
  roles:
    - upgrader
    - wazuh
    - nginx-public

- hosts: lanNginx
  user: root
  vars_files:
    - priv-vars.yaml
  roles:
    - upgrader
    - wazuh
    - nginx-local