- hosts: gitea
  user: oharris
  become: yes
  become_user: root
  vars:
    docker_user: oharris
  roles:
    - upgrader
    - docker
    - guest-agent
    - gitea

- hosts: vault
  user: root
  vars_files:
    - priv-vars.yaml
  roles:
    - upgrader
    - docker
    - vault