- name: Add user to docker group
  user:
    name: oharris
    groups: docker
    append: yes

- name: Create directory for nginx
  file:
    path: /home/oharris/nginx
    state: directory
    owner: oharris
    group: oharris

- name: Create directory for nginx certs
  file:
    path: /home/oharris/nginx/certs
    state: directory
    owner: oharris
    group: oharris

- name: Create directory for nginx
  file:
    path: /home/oharris/nginx/sites-enabled
    state: directory
    owner: oharris
    group: oharris

- name: Copy dockerfile file
  copy:
    src: dockerfile
    dest: /home/oharris/nginx/Dockerfile
    owner: oharris
    group: oharris

- name: Copy docker compose file
  copy:
    src: docker-compose.yaml
    dest: /home/oharris/nginx/docker-compose.yaml
    owner: oharris
    group: oharris

- name: Copy nginx conf
  template:
    src: tunneled.j2
    dest: /home/oharris/nginx/sites-enabled/reverse.conf
    owner: oharris
    group: oharris

- name: Copy nginx key
  copy:
    src: key.key
    dest: /home/oharris/nginx/certs/key.key
    owner: oharris
    group: oharris

- name: Copy dockerfile cert file
  copy:
    src: cert.crt
    dest: /home/oharris/nginx/certs/cert.crt
    owner: oharris
    group: oharris

- name: Start docker Compose
  community.docker.docker_compose_v2:
    project_src: /home/oharris/nginx
    state: restarted
    build: always
