FROM nginx

RUN apt update
RUN apt upgrade -y

RUN apt install fail2ban wget -y
RUN wget -O ngxblocker.sh https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/install-ngxblocker; bash ./ngxblocker.sh -x

RUN rm /etc/nginx/conf.d/default.conf
RUN sed -i '$i include /etc/nginx/sites-enabled/*.conf;' /etc/nginx/nginx.conf
RUN sed -i '$i server_tokens off;' /etc/nginx/nginx.conf