version: "3.9"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - /mnt/nfs/uptime-kuma:/app/data # allows image to popup on any node
    restart: always
