version: '3'
services:
    bit:
        image: vaultwarden/server:latest
        environment:
          LOG_FILE: "/data/logger.txt"
          SIGNUPS_ALLOWED: "false"
          DOMAIN: https://bit.{{domain_name}}
          #ADMIN_TOKEN: pin"
        volumes:
            - ./data/:/data
        ports:
            - "80:80"
        restart: always