- name: Add user to docker group
  user:
    name: oharris
    groups: docker
    append: yes

- name: Create directory for nginx
  file:
    path: /home/oharris/nginx
    state: directory
    owner: oharris
    group: oharris

- name: Create directory for nginx
  file:
    path: /home/oharris/nginx/sites-enabled
    state: directory
    owner: oharris
    group: oharris

- name: Copy gateway docker image
  copy:
    src: gatewayDocker
    dest: /home/oharris/nginx/image
    mode: +x

- name: Import docker image
  shell: docker load -i /home/oharris/nginx/image 

- name: Copy dockerfile file
  copy:
    src: dockerfile
    dest: /home/oharris/nginx/Dockerfile
    owner: oharris
    group: oharris

- name: Copy docker compose file
  template:
    src: docker-compose.yaml
    dest: /home/oharris/nginx/docker-compose.yaml
    owner: oharris
    group: oharris

- name: Copy nginx conf
  template:
    src: public_reverse.conf.j2
    dest: /home/oharris/nginx/sites-enabled/reverse.conf
    owner: oharris
    group: oharris

- name: Copy geo db
  copy:
    src: GeoLite2-Country_20240730.tar.gz
    dest: /home/oharris/nginx/GeoLite2-Country_20240730.tar.gz
    owner: oharris
    group: oharris

- name: Copy dockerfile cert file
  copy:
    src: cert.crt
    dest: /home/oharris/nginx/cert.crt
    owner: oharris
    group: oharris

- name : Start docker Compose
  community.docker.docker_compose_v2:
    project_src: /home/oharris/nginx
    state: restarted
    build: always
