- name: Update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 166400 #two ish days

- name: Install unattended-upgrades and apt-listchanges
  apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Configure unattended-upgrades (all updates)
  copy:
    content: |
      Unattended-Upgrade::Origins-Pattern {
        "origin=Ubuntu,codename=${distro_codename}";
      };
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "05:00";
      Unattended-Upgrade::Automatic-Security-Updates "true";
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Enable automatic updates
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: '0644'