---
- name: Create vault user
  user:
    name: vault
    state: present
    groups: docker
    createhome: yes

- name: Create vault folders
  file:
    path: /home/vault/bit
    state: directory
    owner: vault
    group: vault

- name: Copy docker-compose.yaml file
  template:
    src: docker-compose.yaml
    dest: /home/vault/bit/docker-compose.yaml
    owner: vault
    group: vault

- name: Stop vault
  shell: docker compose down
  args:
    chdir: /home/vault/bit
  become: true
  become_user: vault

- name: Restart vault and pull latest image
  shell: docker compose pull
  args:
    chdir: /home/vault/bit
  become: true
  become_user: vault

- name: Run Docker Compose
  shell: docker compose up -d 
  args:
    chdir: /home/vault/bit
  become: true
  become_user: vault