
- name: Install required packages
  apt:
    name:
      - curl
      - tar
    state: present

- name: Download the install file
  get_url:
    url: https://packages.wazuh.com/4.7/wazuh-install.sh
    dest: /root/wazuh-install.sh


# The rest is installed on the machine