FROM nginx

RUN apt-get install -y ca-certificates

COPY cert.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

RUN apt update
RUN apt upgrade -y

RUN apt install python3-certbot-nginx fail2ban wget -y
RUN wget -O ngxblocker.sh https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/install-ngxblocker; bash ./ngxblocker.sh -x

RUN rm /etc/nginx/conf.d/default.conf
RUN sed -i '$i include /etc/nginx/sites-enabled/*.conf;' /etc/nginx/nginx.conf
RUN sed -i '$i server_tokens off;' /etc/nginx/nginx.conf
#RUN sed -i '$i geoip_country /usr/share/geoip/GeoLite2-Country_20240730;' /etc/nginx/nginx.conf



RUN mkdir -p /usr/share/geoip
COPY GeoLite2-Country_20240730.tar.gz /usr/share/geoip/db.tar.gz
RUN tar -xvzf /usr/share/geoip/db.tar.gz -C /usr/share/geoip/
RUN rm /usr/share/geoip/db.tar.gz
#RUN sed -i '1s/^/load_module modules\/ngx_http_geoip_module.so;\n/' /etc/nginx/nginx.conf
