- name: Install curl and gpg
  apt:
    name:
      - curl
      - gnupg
    state: present

- name: Install Wazuh GPG key
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: Add Wazuh repository
  apt_repository:
    repo: 'deb https://packages.wazuh.com/4.x/apt/ stable main'
    state: present
    filename: wazuh.list
    update_cache: yes

- name: Install Wazuh agent
  apt:
    name: wazuh-agent
    state: present

- name: Configure Wazuh agent
  # block:
  #   - name: Check Wazuh agent config
  #     shell: "cat /var/ossec/etc/ossec.conf | grep -q {{ wazuh_address }}"
  #     ignore_errors: true
  #     register: config_check
  #     changed_when: false

  # - name: Update Wazuh agent config
  ansible.builtin.template: 
    src: config.j2
    dest:  /var/ossec/etc/ossec.conf
    owner: root
    group: wazuh
    mode: '0660'
      # when: config_check.rc != 0


- name: Start Wazuh agent service
  service:
    name: wazuh-agent
    state: restarted
    enabled: yes
