- name: Create directory for authentik
  file:
    path: /root/authentik
    state: directory

- name: Copy docker compose
  copy:
    src: docker-compose.yml
    dest: /root/authentik/docker-compose.yml

# instructions for the env file are here https://docs.goauthentik.io/docs/installation/docker-compose
- name: Copy env file
  copy:
    src: env
    dest: /root/authentik/.env

- name : Stop docker Compose
  community.docker.docker_compose_v2:
    project_src: /root/authentik
    state: absent

- name : Start docker Compose
  community.docker.docker_compose_v2:
    project_src: /root/authentik
    state: present
