---
- name: Get key for nginx repo
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add nginx repo
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/ubuntu/ jammy nginx
    state: present
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
      - wget
      - curl
      - fail2ban
    state: present

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Copy nginx conf
  template:
    src: public_reverse.conf.j2
    dest: /etc/nginx/conf.d/reverse.conf
  notify: restart nginx

- name: test nginx config
  shell: nginx -t


- name: Copy log config
  copy:
    src: log.conf
    dest: /etc/nginx/conf.d/log.conf
  notify: restart nginx
  

- name: Check if ngxblocker installation script exists
  stat:
    path: /usr/local/sbin/install-ngxblocker
  register: ngxblocker_script

- name: download ngnixblocker
  get_url:
    url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/install-ngxblocker
    dest: /usr/local/sbin/install-ngxblocker
    mode: 0755
  when: ngxblocker_script.stat.exists == False

- name: Install ngxblocker
  shell: /usr/local/sbin/install-ngxblocker -x
  when: ngxblocker_script.stat.exists == False

- name: Update ngxblocker
  shell: /usr/local/sbin/update-ngxblocker 
  when: ngxblocker_script.stat.exists == True

- name: Uncomment server_tokens line if it exists in nginx.conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^[[:space:]]*# server_tokens off;'
    line: 'server_tokens off;'
    backrefs: yes  # Enable backreferences in the regexp

- name: Restart nginx
  service:
    name: nginx
    state: restarted




