- name: Add user to docker group
  user:
    name: oharris
    groups: docker
    append: yes

- name: Create directory for caddy
  file:
    path: /home/oharris/caddy
    state: directory
    owner: oharris
    group: oharris

- name: Create directory for caddy config
  file:
    path: /home/oharris/caddy/config
    state: directory
    owner: oharris
    group: oharris

- name: Copy gateway docker image
  copy:
    src: gatewayDocker
    dest: /home/oharris/caddy/gatewayImage
    mode: +x

- name: Import docker image
  shell: docker load -i /home/oharris/caddy/gatewayImage 

- name: Copy caddy docker image
  copy:
    src: caddyImage
    dest: /home/oharris/caddy/caddyImage
    mode: +x

- name: Import docker caddy image
  shell: docker load -i /home/oharris/caddy/caddyImage 


- name: Copy docker compose file
  template:
    src: docker-compose.yaml
    dest: /home/oharris/caddy/docker-compose.yaml
    owner: oharris
    group: oharris

- name: Copy conf
  template:
    src: Caddyfile
    dest: /home/oharris/caddy/Caddyfile
    owner: oharris
    group: oharris



- name : Stop docker Compose
  community.docker.docker_compose_v2:
    project_src: /home/oharris/caddy
    state: absent

- name : Start docker Compose
  community.docker.docker_compose_v2:
    project_src: /home/oharris/caddy
    state: present
